<a href="https://colab.research.google.com/github/ademaldemir/DataScienceWithPython/blob/main/Lecture_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises on pandas library

In [ ]:
# First download the stockoverflow developer survey dataset
# You can find the survey responsedata per year : https://insights.stackoverflow.com/survey 
# We will use 2020 dataset : https://drive.google.com/file/d/1dfGerWeWkcyQ9GX9x20rdSGj7WtEpzBB/view?usp=sharing

#First import pandas 

import pandas as pd 

#Copy the csv files into a folder in your Desktop
#If your Python code in the same folder, you can simply specify the name of the file that you want to read.
#Otherwise,
#You need to specify the path as 'DeveloperData/survey_results_public.csv' if the file is stored under DeveloperData

#Reading from csv files
mydf=pd.read_csv('/content/drive/My Drive/Master Courses/Data Science with Python/developer_survey_2020/survey_results_public.csv')
mydf

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,NaN,NaN,NaN,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"Iâ€™m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not at all important/not necessary,Curious about other opportunities;Wanting to w...,NaN,Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Linux-based,20 to 99 employees,NaN,NaN,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64456,64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,Senior executive/VP,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a decade,NaN,NaN,NaN,NaN,Start a free trial,Amused,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64457,64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64458,64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,NaN,NaN,NaN,NaN,Primary/elementary school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64459,64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,DynamoDB;Elasticsearch;MongoDB;MySQL;PostgreSQL,Oracle,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,HTML/CSS,Node.js,NaN,Github;Gitlab,Confluence;Jira;Slack;Microsoft Teams,NaN,NaN,NaN,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow,Windows,NaN,NaN,Linux;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
64460,65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NaN,MariaDB;Microsoft SQL Server,MariaDB;Microsoft SQL Server;MySQL;Oracle,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,C#;HTML/CSS;Java;JavaScript;SQL,C#;HTML/CSS;Java;JavaScript;SQL,.NET Core;Xamarin,.NET;.NET Core,Github;Microsoft Teams,Github,NaN,NaN,Critically important,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Indifferent,NaN,Meditate;Visit Stack Overflow;Go for a walk or...,Windows,NaN,Arduino;Linux;Raspberry Pi;Windows,Android;Arduino;Linux;Raspberry Pi;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [ ]:
#Reading from csv files
mydfschema=pd.read_csv('/content/drive/My Drive/Master Courses/Data Science with Python/developer_survey_2020/survey_results_schema.csv')
mydfschema

,Column,QuestionText
0,Respondent,Randomized respondent ID number (not in order ...
1,MainBranch,Which of the following options best describes ...
2,Hobbyist,Do you code as a hobby?
3,Age,What is your age (in years)? If you prefer not...
4,Age1stCode,At what age did you write your first line of c...
5,CompFreq,"Is that compensation weekly, monthly, or yearly?"
6,CompTotal,What is your current total compensation (salar...
7,ConvertedComp,Salary converted to annual USD salaries using ...
8,Country,Where do you live?
9,CurrencyDesc,Which currency do you use day-to-day? If your ...
10,CurrencySymbol,Which currency do you use day-to-day? If your ...
11,DatabaseDesireNextYear,Which database environments have you done exte...
12,DatabaseWorkedWith,Which database environments have you done exte...
13,DevType,Which of the following describe you? Please se...
14,EdLevel,Which of the following best describes the high...
15,Employment,Which of the following best describes your cur...
16,Ethnicity,"Which of the following describe you, if any? P..."
17,Gender,"Which of the following describe you, if any? P..."
18,JobFactors,Imagine that you are deciding between two job ...
19,JobSat,How satisfied are you with your current job? (...
20,JobSeek,Which of the following best describes your cur...
21,LanguageDesireNextYear,"Which programming, scripting, and markup langu..."
22,LanguageWorkedWith,"Which programming, scripting, and markup langu..."
23,MiscTechDesireNextYear,"Which other frameworks, libraries, and tools h..."
24,MiscTechWorkedWith,"Which other frameworks, libraries, and tools h..."
25,NEWCollabToolsDesireNextYear,Which collaboration tools have you done extens...
26,NEWCollabToolsWorkedWith,Which collaboration tools have you done extens...
27,NEWDevOps,Does your company have a dedicated DevOps person?
28,NEWDevOpsImpt,How important is the practice of DevOps to sca...
29,NEWEdImpt,"How important is a formal education, such as a..."
30,NEWJobHunt,"In general, what drives you to look for a new ..."
31,NEWJobHuntResearch,"When job searching, how do you learn more abou..."
32,NEWLearn,How frequently do you learn a new language or ...
33,NEWOffTopic,Do you think Stack Overflow should relax restr...
34,NEWOnboardGood,Do you think your company has a good onboardin...
35,NEWOtherComms,Are you a member of any other online developer...
36,NEWOvertime,How often do you work overtime or beyond the f...
37,NEWPurchaseResearch,"When buying a new tool or software, how do you..."
38,NEWPurpleLink,You search for a coding solution online and th...
39,NEWSOSites,Which of the following Stack Overflow sites ha...
40,NEWStuck,What do you do when you get stuck on a problem...
41,OpSys,What is the primary operating system in which ...
42,OrgSize,Approximately how many people are employed by ...
43,PlatformDesireNextYear,Which platforms have you done extensive develo...
44,PlatformWorkedWith,Which platforms have you done extensive develo...
45,PurchaseWhat,"What level of influence do you, personally, ha..."
46,Sexuality,"Which of the following describe you, if any? P..."
47,SOAccount,Do you have a Stack Overflow account?
48,SOComm,Do you consider yourself a member of the Stack...
49,SOPartFreq,How frequently would you say you participate i...
50,SOVisitFreq,How frequently would you say you visit Stack O...
51,SurveyEase,How easy or difficult was this survey to compl...
52,SurveyLength,How do you feel about the length of the survey...
53,Trans,Are you transgender?
54,UndergradMajor,What was your primary field of study?
55,WebframeDesireNextYear,Which web frameworks have you done extensive d...
56,WebframeWorkedWith,Which web frameworks have you done extensive d...
57,WelcomeChange,"Compared to last year, how welcome do you feel..."
58,WorkWeekHrs,"On average, how many hours per week do you wor..."
59,YearsCode,"Including any education, how many years have y..."
60,YearsCodePro,"NOT including education, how many years have y..."

In [ ]:
#Changing the display settings so that you can see at most 61 columns

pd.set_option('display.max_columns', 61)
mydf

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,NaN,NaN,NaN,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"Iâ€™m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not at all important/not necessary,Curious about other opportunities;Wanting to w...,NaN,Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Linux-based,20 to 99 employees,NaN,NaN,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64456,64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,Senior executive/VP,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a decade,NaN,NaN,NaN,NaN,Start a free trial,Amused,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64457,64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64458,64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,NaN,NaN,NaN,NaN,Primary/elementary school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64459,64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,DynamoDB;Elasticsearch;MongoDB;MySQL;PostgreSQL,Oracle,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,HTML/CSS,Node.js,NaN,Github;Gitlab,Confluence;Jira;Slack;Microsoft Teams,NaN,NaN,NaN,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow,Windows,NaN,NaN,Linux;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
64460,65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NaN,MariaDB;Microsoft SQL Server,MariaDB;Microsoft SQL Server;MySQL;Oracle,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,C#;HTML/CSS;Java;JavaScript;SQL,C#;HTML/CSS;Java;JavaScript;SQL,.NET Core;Xamarin,.NET;.NET Core,Github;Microsoft Teams,Github,NaN,NaN,Critically important,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Indifferent,NaN,Meditate;Visit Stack Overflow;Go for a walk or...,Windows,NaN,Arduino;Linux;Raspberry Pi;Windows,Android;Arduino;Linux;Raspberry Pi;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [ ]:
#Changing the display settings so that you can see at most 61rows

pd.set_option('display.max_rows', 61)
mydfschema

,Column,QuestionText
0,Respondent,Randomized respondent ID number (not in order ...
1,MainBranch,Which of the following options best describes ...
2,Hobbyist,Do you code as a hobby?
3,Age,What is your age (in years)? If you prefer not...
4,Age1stCode,At what age did you write your first line of c...
5,CompFreq,"Is that compensation weekly, monthly, or yearly?"
6,CompTotal,What is your current total compensation (salar...
7,ConvertedComp,Salary converted to annual USD salaries using ...
8,Country,Where do you live?
9,CurrencyDesc,Which currency do you use day-to-day? If your ...
10,CurrencySymbol,Which currency do you use day-to-day? If your ...
11,DatabaseDesireNextYear,Which database environments have you done exte...
12,DatabaseWorkedWith,Which database environments have you done exte...
13,DevType,Which of the following describe you? Please se...
14,EdLevel,Which of the following best describes the high...
15,Employment,Which of the following best describes your cur...
16,Ethnicity,"Which of the following describe you, if any? P..."
17,Gender,"Which of the following describe you, if any? P..."
18,JobFactors,Imagine that you are deciding between two job ...
19,JobSat,How satisfied are you with your current job? (...
20,JobSeek,Which of the following best describes your cur...
21,LanguageDesireNextYear,"Which programming, scripting, and markup langu..."
22,LanguageWorkedWith,"Which programming, scripting, and markup langu..."
23,MiscTechDesireNextYear,"Which other frameworks, libraries, and tools h..."
24,MiscTechWorkedWith,"Which other frameworks, libraries, and tools h..."
25,NEWCollabToolsDesireNextYear,Which collaboration tools have you done extens...
26,NEWCollabToolsWorkedWith,Which collaboration tools have you done extens...
27,NEWDevOps,Does your company have a dedicated DevOps person?
28,NEWDevOpsImpt,How important is the practice of DevOps to sca...
29,NEWEdImpt,"How important is a formal education, such as a..."
30,NEWJobHunt,"In general, what drives you to look for a new ..."
31,NEWJobHuntResearch,"When job searching, how do you learn more abou..."
32,NEWLearn,How frequently do you learn a new language or ...
33,NEWOffTopic,Do you think Stack Overflow should relax restr...
34,NEWOnboardGood,Do you think your company has a good onboardin...
35,NEWOtherComms,Are you a member of any other online developer...
36,NEWOvertime,How often do you work overtime or beyond the f...
37,NEWPurchaseResearch,"When buying a new tool or software, how do you..."
38,NEWPurpleLink,You search for a coding solution online and th...
39,NEWSOSites,Which of the following Stack Overflow sites ha...
40,NEWStuck,What do you do when you get stuck on a problem...
41,OpSys,What is the primary operating system in which ...
42,OrgSize,Approximately how many people are employed by ...
43,PlatformDesireNextYear,Which platforms have you done extensive develo...
44,PlatformWorkedWith,Which platforms have you done extensive develo...
45,PurchaseWhat,"What level of influence do you, personally, ha..."
46,Sexuality,"Which of the following describe you, if any? P..."
47,SOAccount,Do you have a Stack Overflow account?
48,SOComm,Do you consider yourself a member of the Stack...
49,SOPartFreq,How frequently would you say you participate i...
50,SOVisitFreq,How frequently would you say you visit Stack O...
51,SurveyEase,How easy or difficult was this survey to compl...
52,SurveyLength,How do you feel about the length of the survey...
53,Trans,Are you transgender?
54,UndergradMajor,What was your primary field of study?
55,WebframeDesireNextYear,Which web frameworks have you done extensive d...
56,WebframeWorkedWith,Which web frameworks have you done extensive d...
57,WelcomeChange,"Compared to last year, how welcome do you feel..."
58,WorkWeekHrs,"On average, how many hours per week do you wor..."
59,YearsCode,"Including any education, how many years have y..."
60,YearsCodePro,"NOT including education, how many years have y..."

In [ ]:
# shape attribute gives the number of rows and columns
mydf.shape

# We have 64461 rows and 61 columns

(64461, 61)

In [ ]:
# For more information about a given dataframe, you can call info() method.

mydf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64461 entries, 0 to 64460
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Respondent                    64461 non-null  int64
 1   MainBranch                    64162 non-null  object
 2   Hobbyist                      64416 non-null  object
 3   Age                           45446 non-null  float64
 4   Age1stCode                    57900 non-null  object
 5   CompFreq                      40069 non-null  object
 6   CompTotal                     34826 non-null  float64
 7   ConvertedComp                 34756 non-null  float64
 8   Country                       64072 non-null  object
 9   CurrencyDesc                  45472 non-null  object
 10  CurrencySymbol                45472 non-null  object
 11  DatabaseDesireNextYear        44070 non-null  object
 12  DatabaseWorkedWith            49537 non-null  object
 13  DevType                       49370 non-null  object
 14  EdLevel                       57431 non-null  object
 15  Employment                    63854 non-null  object
 16  Ethnicity                     45948 non-null  object
 17  Gender                        50557 non-null  object
 18  JobFactors                    49349 non-null  object
 19  JobSat                        45194 non-null  object
 20  JobSeek                       51727 non-null  object
 21  LanguageDesireNextYear        54113 non-null  object
 22  LanguageWorkedWith            57378 non-null  object
 23  MiscTechDesireNextYear        42379 non-null  object
 24  MiscTechWorkedWith            40314 non-null  object
 25  NEWCollabToolsDesireNextYear  47287 non-null  object
 26  NEWCollabToolsWorkedWith      52883 non-null  object
 27  NEWDevOps                     42686 non-null  object
 28  NEWDevOpsImpt                 41732 non-null  object
 29  NEWEdImpt                     48465 non-null  object
 30  NEWJobHunt                    42286 non-null  object
 31  NEWJobHuntResearch            41022 non-null  object
 32  NEWLearn                      56156 non-null  object
 33  NEWOffTopic                   50804 non-null  object
 34  NEWOnboardGood                42623 non-null  object
 35  NEWOtherComms                 57205 non-null  object
 36  NEWOvertime                   43231 non-null  object
 37  NEWPurchaseResearch           37321 non-null  object
 38  NEWPurpleLink                 54803 non-null  object
 39  NEWSOSites                    58275 non-null  object
 40  NEWStuck                      54983 non-null  object
 41  OpSys                         56228 non-null  object
 42  OrgSize                       44334 non-null  object
 43  PlatformDesireNextYear        50605 non-null  object
 44  PlatformWorkedWith            53843 non-null  object
 45  PurchaseWhat                  39364 non-null  object
 46  Sexuality                     43992 non-null  object
 47  SOAccount                     56805 non-null  object
 48  SOComm                        56476 non-null  object
 49  SOPartFreq                    46792 non-null  object
 50  SOVisitFreq                   56970 non-null  object
 51  SurveyEase                    51802 non-null  object
 52  SurveyLength                  51701 non-null  object
 53  Trans                         49345 non-null  object
 54  UndergradMajor                50995 non-null  object
 55  WebframeDesireNextYear        40024 non-null  object
 56  WebframeWorkedWith            42279 non-null  object
 57  WelcomeChange                 52683 non-null  object
 58  WorkWeekHrs                   41151 non-null  float64
 59  YearsCode                     57684 non-null  object
 60  YearsCodePro                  46349 non-null  object
dtypes: float64(4), int64(1), object(56)
memory usage: 30.0+ MB

In [ ]:
mydf.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,NaN,NaN,NaN,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"Iâ€™m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not at all important/not necessary,Curious about other opportunities;Wanting to w...,NaN,Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Linux-based,20 to 99 employees,NaN,NaN,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

In [ ]:
#See the content of first n rows, you can specify the value of n as an argument to head ()

mydf.head(10) # Show content of the first 10 row

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,NaN,NaN,NaN,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"Iâ€™m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not at all important/not necessary,Curious about other opportunities;Wanting to w...,NaN,Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Linux-based,20 to 99 employees,NaN,NaN,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
5,6,I am a developer by profession,No,NaN,14,NaN,NaN,NaN,Germany,European Euro,EUR,NaN,NaN,"Designer;Developer, front-end;Developer, mobile","Secondary school (e.g. American high school, G...",Employed full-time,White or of European descent,Man,Diversity of the company or organization;Langu...,Slightly satisfied,I am not interested in new job opportunities,HTML/CSS;Java;JavaScript,HTML/CSS;Java;JavaScript,NaN,NaN,Github;Slack,Confluence;Github;Slack;Trello,Not sure,NaN,Fairly important,NaN,NaN,Once a year,No,No,No,Never,Ask developers I know/work with;Read ratings o...,Amused,Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Watch help / t...,Windows,NaN,Android,Android;Docker;WordPress,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,A few times per week,Neither easy nor difficult,Appropriate in length,NaN,NaN,React.js,NaN,NaN,NaN,6,4
6,7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,USD,NaN,NaN,"Developer, back-end;Developer, front-end;Devel...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very satisfied,"Iâ€™m not actively looking, but I am open to new...",C#;HTML/CSS;PHP,C#;HTML/CSS;PHP,NaN,NaN,NaN,NaN,Yes,Extremely important,Very important,Better compensation;Growth or leadership oppor...,"Read company media, such as employee blogs or ...",Every few months,Yes,Yes,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Windows,20 to 99 employees,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
7,8,I am a developer by profession,Yes,36.0,12,Yearly,116000.0,116000.0,United States,United States dollar,USD,MongoDB,MariaDB;MySQL;Redis,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Remote work options;Opportunities for professi...,Slightly dissatisfied,"Iâ€™m not actively looking, but I am open to new...",JavaScript,Python;SQL,Unity 3D,Ansible,NaN,Confluence;Jira;Github;Slack;Microsoft Teams;G...,Yes,Extremely important,Not at all important/not necessary,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Yes,No,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,Linux-based,20 to 99 employees,iOS;Slack Apps and Integrations,Docker,I have some influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;React.js;Vue.js,Flask,Just as welcome now as I felt last year,39.0,17,13
8,9,I am a developer by profession,No,30.0,20,NaN,NaN,NaN,Tunisia,United States dollar,USD,NaN,NaN,"Developer, full-stack","Professional degree (JD, MD, etc.)","Independent contractor, freelancer, or self-em...",NaN,Man,Diversity of the company or organization;Remot...,Very dissatisfied,"Iâ€™m not actively looking, but I am open to new...",Python;Rust,HTML/CSS;JavaScript;PHP,NaN,NaN,NaN,"Github;Slack;Trello;Google Suite (Docs, Meet, ...",NaN,NaN,Very important,Curious about other opportunities;Growth or le...,NaN,Once a year,No,Yes,No,Occasionally: 1-2 days per quarter but less th...,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Meditate,Windows,"Just me - I am a freelancer, sole proprietor, ...",NaN,WordPress,NaN,Straight / Heterosexual,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular.js,jQuery,Just as welcome now as I felt last year,50.0,6,4
9,10,I am a developer by profession,Yes,22.0,14,Yearly,25000.0,32315.0,United Kingdom,Pound sterling,GBP,Microsoft SQL Server,Microsoft SQL Server,"Database administrator;Developer, full-stack;D...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;How widely us...,Very satisfied,"Iâ€™m not actively looking, but I am open to new...",HTML/CSS;Java;JavaScript;Python;R;SQL,HTML/CSS;Java;JavaScript;Python;SQL,Pandas;TensorFlow,Pandas,Github;Microsoft Teams,Github;Microsoft Teams,No,Neutral,Fairly important,Curious about other opportunities;Better compe...,Company reviews from third party sites (e.g. G...,Every few months,Yes,Onboarding? What onboarding?,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow,Windows,2 to 9 employees,Android;Linux;Raspberry Pi;Windows,Android;Linux;Raspberry Pi;Windows,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,Easy,Appropriate in length,No,Mathematics or statistics,Flask;jQuery,Flask;jQuery,Somewhat more welcome now than last year,36.0,8,4

In [ ]:
# In order to see the last rows, similarly you can call tail() method
mydf.tail()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
64456,64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,Senior executive/VP,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a decade,NaN,NaN,NaN,NaN,Start a free trial,Amused,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64457,64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64458,64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,NaN,NaN,NaN,NaN,Primary/elementary school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64459,64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,DynamoDB;Elasticsearch;MongoDB;MySQL;PostgreSQL,Oracle,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,HTML/CSS,Node.js,NaN,Github;Gitlab,Confluence;Jira;Slack;Microsoft Teams,NaN,NaN,NaN,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow,Windows,NaN,NaN,Linux;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
64460,65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NaN,MariaDB;Microsoft SQL Server,MariaDB;Microsoft SQL Server;MySQL;Oracle,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,C#;HTML/CSS;Java;JavaScript;SQL,C#;HTML/CSS;Java;JavaScript;SQL,.NET Core;Xamarin,.NET;.NET Core,Github;Microsoft Teams,Github,NaN,NaN,Critically important,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Indifferent,NaN,Meditate;Visit Stack Overflow;Go for a walk or...,Windows,NaN,Arduino;Linux;Raspberry Pi;Windows,Android;Arduino;Linux;Raspberry Pi;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [ ]:
mydf.tail(10) # last ten rows

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
64451,64104,NaN,Yes,NaN,19,NaN,NaN,NaN,Poland,NaN,NaN,NaN,NaN,Data scientist or machine learning specialist,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fairly important,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,A few times per month or weekly,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,2,NaN
64452,64236,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64453,64330,NaN,Yes,NaN,5,NaN,NaN,NaN,Thailand,NaN,NaN,NaN,NaN,"Data or business analyst;Developer, mobile;Sen...",Primary/elementary school,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS,C++;HTML/CSS,.NET,.NET,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial,"Hello, old friend",Stack Overflow for Teams (private Q&A for orga...,Watch help / tutorial videos,MacOS,NaN,iOS,iOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
64454,64480,NaN,Yes,NaN,21,NaN,NaN,NaN,Morocco,NaN,NaN,NaN,NaN,NaN,I never completed any formal education,Student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not sure/can't remember,"No, not really",NaN,Less than once per month or monthly,NaN,NaN,NaN,NaN,NaN,NaN,Just as welcome now as I felt last year,NaN,3,NaN
64455,64567,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Netherlands,NaN,NaN,Microsoft SQL Server,NaN,NaN,NaN,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,Java,NaN,Ansible,NaN,NaN,Github,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ASP.NET Core,NaN,NaN,NaN,NaN
64456,64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,Senior executive/VP,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a decade,NaN,NaN,NaN,NaN,Start a free trial,Amused,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64457,64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64458,64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,NaN,NaN,NaN,NaN,Primary/elementary school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64459,64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,DynamoDB;Elasticsearch;MongoDB;MySQL;PostgreSQL,Oracle,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,HTML/CSS,Node.js,NaN,Github;Gitlab,Confluence;Jira;Slack;Microsoft Teams,NaN,NaN,NaN,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow,Windows,NaN,NaN,Linux;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
64460,65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NaN,MariaDB;Microsoft SQL Server,MariaDB;Microsoft SQL Server;MySQL;Oracle,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,C#;HTML/CSS;Java;JavaScript;SQL,C#;HTML/CSS;Java;JavaScript;SQL,.NET Core;Xamarin,.NET;.NET Core,Github;Microsoft Teams,Github,NaN,NaN,Critically important,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Indifferent,NaN,Meditate;Visit Stack Overflow;Go for a walk or...,Windows,NaN,Arduino;Linux;Raspberry Pi;Windows,Android;Arduino;Linux;Raspberry Pi;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [ ]:
#We can also create a dataframe from a dictionary

#Create a dictionary

student={
    "Id":["S1","S12","S15","S20"],
    "Name": ["Lale","Ali","Veli","Dilara"],
    "Surname": ["Al","Al","Av","Ad"],
    "Grade":[10,4,6,8]
}

student

{'Grade': [10, 4, 6, 8],
 'Id': ['S1', 'S12', 'S15', 'S20'],
 'Name': ['Lale', 'Ali', 'Veli', 'Dilara'],
 'Surname': ['Al', 'Al', 'Av', 'Ad']}

In [ ]:
#Create a dataframe by using student dictionary
mystudents=pd.DataFrame(student)
mystudents

    Id    Name Surname  Grade
0   S1    Lale      Al     10
1  S12     Ali      Al      4
2  S15    Veli      Av      6
3  S20  Dilara      Ad      8

In [ ]:
# Accessing columns: 

#First way to access a specific column - [] notation
mystudents["Surname"] # accessing a column of the data frame

0    Al
1    Al
2    Av
3    Ad
Name: Surname, dtype: object

In [ ]:
#Second way to access a specific column - . notation
mystudents.Surname

0    Al
1    Al
2    Av
3    Ad
Name: Surname, dtype: object

In [ ]:
# Some developers prefers the [] notation since . notation may be problematic 
# when the datafame has a column which is has the same name as one of attributes of DataFrame. For example, count is
# is an attribute of the datafame object. Therefore, if you want to access a column named "count", 
# you should use [] notation. 

#Accessing multiple columns 
mystudents[["Name", "Surname"]]

     Name Surname
0    Lale      Al
1     Ali      Al
2    Veli      Av
3  Dilara      Ad

In [ ]:
#Accessing a particular row
#If you want to access the row by referring its index, iloc (index location)
mystudents.iloc[2]

Id          S15
Name       Veli
Surname      Av
Grade         6
Name: 2, dtype: object

In [ ]:
#For multiple rows you can specify an array of indices
mystudents.iloc[[2,3]]

    Id    Name Surname  Grade
2  S15    Veli      Av      6
3  S20  Dilara      Ad      8

In [ ]:
#You can also use slicing 
mystudents.iloc[1:2]

    Id Name Surname  Grade
1  S12  Ali      Al      4

In [ ]:
#You can specify the column of the selected rows similarly
mystudents.iloc[ [0,1], [2]] #returns the thirds colum of those rows

  Surname
0      Al
1      Al

In [ ]:
#You can use loc in order to access by specifying label 
#Labels are bold in the dataframe so indices of rows are the labels here. 
mystudents.loc[0]

Id           S1
Name       Lale
Surname      Al
Grade        10
Name: 0, dtype: object

In [ ]:
mystudents.loc[0,'Id']  #the value of the column named Id in the first

'S1'

In [ ]:
# More exercises mydf
#Slicing is slightly different here. End index is inclusive !
mystudents.loc[1:2]

    Id  Name Surname  Grade
1  S12   Ali      Al      4
2  S15  Veli      Av      6

In [ ]:
# More exercise with the dataframe of stockoverflow responses
mydf.iloc[0]
mydf.iloc[[0,1]]
mydf.iloc[ [0,1], [2]]
mydf.loc[0, 'Hobbyist']
mydf.loc[0:2, 'Hobbyist':'Employment']

,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment
0,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em..."
1,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time
2,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Count the unique values in a column
mydf['Hobbyist'].value_counts()

Yes    50388
No     14028
Name: Hobbyist, dtype: int64

In [ ]:
#Filtering data in DataFrames

filt=mydf['Country']=='Turkey'
mydf[filt]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
292,294,I am a developer by profession,Yes,40.0,19,Monthly,17000.0,33528.0,Turkey,Turkish lira,TRY,MongoDB,IBM DB2;Microsoft SQL Server;Oracle,"Developer, back-end;Developer, full-stack","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,"Iâ€™m not actively looking, but I am open to new...",C#;JavaScript,C#;Java;JavaScript;SQL,.NET;.NET Core;Node.js;React Native,.NET;Node.js;React Native,Github,Jira;Github,Yes,Extremely important,Fairly important,Better compensation;Wanting to work with new t...,Company reviews from third party sites (e.g. G...,Once a year,No,Yes,No,Rarely: 1-2 days per year or less,NaN,Annoyed,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow,Windows,"10,000 or more employees",Heroku,Heroku,I have little or no influence,NaN,Yes,"Yes, definitely",Daily or almost daily,Daily or almost daily,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",Angular;ASP.NET;ASP.NET Core;Express;React.js,Angular;ASP.NET;Express;React.js,Somewhat less welcome now than last year,40.0,20,14
410,412,I am a developer by profession,Yes,23.0,11,Monthly,110000.0,216960.0,Turkey,Turkish lira,TRY,Elasticsearch;MongoDB;PostgreSQL;Redis,Firebase;Microsoft SQL Server;MongoDB;MySQL;Or...,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,Middle Eastern;White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,HTML/CSS;Java;JavaScript;SQL;TypeScript,C;C#;HTML/CSS;Java;JavaScript;Kotlin;Python;SQL,Pandas,Node.js,Jira;Github;Gitlab,Confluence;Jira;Github,Not sure,Neutral,Very important,Just because;Curious about other opportunities...,"Read company media, such as employee blogs or ...",Every few months,Yes,Onboarding? What onboarding?,Yes,Sometimes: 1-2 days per month but less than we...,Ask developers I know/work with;Visit develope...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,Windows,"5,000 to 9,999 employees",Docker;Linux;Windows,Android;Linux;Windows,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;React.js;Spring,ASP.NET;jQuery;React.js;Spring,Just as welcome now as I felt last year,40.0,5,Less than 1 year
550,552,I am a developer by profession,No,25.0,16,Yearly,3500.0,575.0,Turkey,Turkish lira,TRY,MySQL;Oracle;SQLite,Firebase;MongoDB,"Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,"Languages, frameworks, and other technologies ...",Very satisfied,"Iâ€™m not actively looking, but I am open to new...",SQL,Objective-C;Swift,NaN,NaN,Jira,"Github;Slack;Trello;Google Suite (Docs, Meet, ...",No,Neutral,Very important,Curious about other opportunities;Wanting to w...,"Read company media, such as employee blogs or ...",Once a year,NaN,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,10 to 19 employees,Raspberry Pi,iOS;MacOS,I have little or no influence,Straight / Heterosexual,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,Daily or almost daily,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,10.0,6,2
647,649,I am a developer by profession,Yes,23.0,5,NaN,NaN,NaN,Turkey,NaN,NaN,Firebase;MongoDB;Redis,Firebase;Microsoft SQL Server;MongoDB;MySQL,NaN,Some college/university study without earning ...,Student,White or of European descent,Man,"Flex time or a flexible schedule;Languages, fr...",NaN,"Iâ€™m not actively looking, but I am open to new...",C#;Dart;HTML/CSS;Java;JavaScript;Python;TypeSc...,C#;HTML/CSS;Java;JavaScript;SQL,.NET;.NET Core;Node.js;TensorFlow;Torch/PyTorc...,.NET;.NET Core;Node.js;Unity 3D,"Github;Gitlab;Slack;Trello;Google Suite (Docs,...",Github;Gitlab;Slack;Trello,NaN,NaN,NaN,Wanting to share accomplishments with a wider ...,Personal network - friends or family;Read othe...,Every few months,Not sure,NaN,Yes,NaN,Ask developers I know/work with;Visit develope...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,NaN,Android;Arduino;AWS;Docker;Heroku;Kubernetes;M...,Android;Heroku;MacOS;Slack Apps and Integrations,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,A few times per week,Neither easy nor difficult,Appropriate in length,No,NaN,Express;jQuery;React.js,Express;jQuery;React.js,Just as welcome now as I felt last year,NaN,3,NaN
802,804,I am a developer by profession,Yes,NaN,15,Yearly,4000.0,657.0,Turkey,Turkish lira,TRY,Oracle;PostgreSQL,Firebase;MySQL;SQLite,"Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Neither satisfied nor dissatisfied,"Iâ€™m not actively looking, but I am open to new...",Dart;Java;Kotlin,HTML/CSS;JavaScript;TypeScript,Flutter;React Native,NaN,Jira,Github;Gitlab;Slack;Trello,No,Extremely important,Very important,Having a bad day (or week or month) at work;Cu...,"Read company media, such as employee blogs or ...",Every few months,Not sure,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,MacOS,20 to 99 employees,iOS,MacOS;Windows,I have little or no influence,NaN,Yes,"No, not really",I have never participated in Q&A on Stack Over...,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,Angular;Angular.js;jQuery;React.js,Just as welcome now as I felt last year,45.0,10,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63567,64990,"I am not primarily a developer, but I write co...",Yes,NaN,17,Weekly,NaN,NaN,Turkey,United States dollar,USD,NaN,Firebase,"Database administrator;Designer;Developer, bac...",Primary/elementary school,Employed part-time,NaN,NaN,Office environment or company culture,Very dissatisfied,I am actively looking for a job,C#,C;Python,NaN,Pandas,NaN,Jira;Github;Stack Overflow for Teams,Yes,Neutral,Very important,Just because;Better work/life balance;Wanting ...,Personal network - friends or family;Directly ...,Once a year,NaN,Yes,Yes,Often: 1-2 days per week or more,Ask developers I know/work with,Annoyed,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow,Linux-based,100 to 499 employees,NaN,Android;Arduino;Linux,I have a great deal of influence,NaN,Yes,"No, not at all",I have never participated in Q&A on Stack Over...,Daily or almost daily,NaN,NaN,NaN,NaN,NaN,Django,NaN,NaN,2,1
63781,65220,I am a developer by profession,Yes,NaN,NaN,NaN,NaN,NaN,Turkey,NaN,NaN,Elasticsearch;Firebase;MongoDB;MySQL;PostgreSQ...,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL;...,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Dart;Go;PHP;Python;TypeScript,C#;JavaScript;PHP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Every few months,NaN,NaN,Yes,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"No, not really",I have never participated in Q&A on Stack Over...,Daily or almost daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63975,65436,I am a developer by profession,Yes,NaN,NaN,NaN,NaN,NaN,Turkey,NaN,NaN,NaN,NaN,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fairly important,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"A social science (such as anthropology, psycho...",NaN,NaN,NaN,NaN,NaN,NaN
64133,65609,I code primarily as a hobby,Yes,NaN,NaN,NaN,NaN,NaN,Turkey,NaN,NaN,PostgreSQL,Microsoft SQL Server,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Python;R,C#;HTML/CSS;SQL,.NET Core,.NET,Github;Gitlab;Stack Overflow for Teams,Confluence;Jira,NaN,NaN,NaN,NaN,NaN,Once every few years,Not sure,NaN,No,NaN,Start a free trial,Annoyed,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow,Windows,NaN,Android,Windows,NaN,NaN,No,"Yes, somewhat",NaN,A few times per month or weekly,NaN,NaN,NaN,NaN,ASP.NET Core,ASP.NET,Somewhat more welcome now than last year,NaN,NaN,NaN
64166,1264,NaN,Yes,NaN,16,NaN,NaN,NaN,Turkey,NaN,NaN,MySQL;SQLite,MySQL;SQLite,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)","Not employed, and not looking for work",NaN,NaN,NaN,NaN,NaN,C++;Java;Kotlin;Python;SQL;Swift,C++;Java;Kotlin;Python;SQL;Swift,Node.js,Node.js,Github,Github,NaN,NaN,Very important,NaN,NaN,NaN,Not sure,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Annoyed,Stack Overflow (public Q&A for anyone who code...,Meditate;Visit Stack Overflow;Watch help / tut...,Linux-based,NaN,Android;iOS;Linux;Raspberry Pi,Android;iOS;Linux;Raspberry Pi,NaN,NaN,Yes,"Yes, definitely",Daily or almost daily,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,Laravel,A lot less welcome now than last year,NaN,30,NaN

In [ ]:
mydf.loc[filt]
mydf.loc[filt,'Age']
mydf.loc[filt, ['Age','ConvertedComp','DevType']]

        Age  ConvertedComp                                            DevType
292    40.0        33528.0          Developer, back-end;Developer, full-stack
410    23.0       216960.0  Developer, back-end;Developer, desktop or ente...
550    25.0          575.0                                  Developer, mobile
647    23.0            NaN                                                NaN
802     NaN          657.0                                  Developer, mobile
...     ...            ...                                                ...
63567   NaN            NaN  Database administrator;Designer;Developer, bac...
63781   NaN            NaN                                                NaN
63975   NaN            NaN                                                NaN
64133   NaN            NaN                                                NaN
64166   NaN            NaN                                                NaN

[777 rows x 3 columns]

In [ ]:
#Specifying more conditions
# & : and
# | :  or 
#  ~ : not

filt= (mydf['Country']=='Turkey') & (mydf['DevType'].str.contains('Developer', na=False))
mydf.loc[filt]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
292,294,I am a developer by profession,Yes,40.0,19,Monthly,17000.0,33528.0,Turkey,Turkish lira,TRY,MongoDB,IBM DB2;Microsoft SQL Server;Oracle,"Developer, back-end;Developer, full-stack","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,"Iâ€™m not actively looking, but I am open to new...",C#;JavaScript,C#;Java;JavaScript;SQL,.NET;.NET Core;Node.js;React Native,.NET;Node.js;React Native,Github,Jira;Github,Yes,Extremely important,Fairly important,Better compensation;Wanting to work with new t...,Company reviews from third party sites (e.g. G...,Once a year,No,Yes,No,Rarely: 1-2 days per year or less,NaN,Annoyed,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow,Windows,"10,000 or more employees",Heroku,Heroku,I have little or no influence,NaN,Yes,"Yes, definitely",Daily or almost daily,Daily or almost daily,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",Angular;ASP.NET;ASP.NET Core;Express;React.js,Angular;ASP.NET;Express;React.js,Somewhat less welcome now than last year,40.0,20,14
410,412,I am a developer by profession,Yes,23.0,11,Monthly,110000.0,216960.0,Turkey,Turkish lira,TRY,Elasticsearch;MongoDB;PostgreSQL;Redis,Firebase;Microsoft SQL Server;MongoDB;MySQL;Or...,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,Middle Eastern;White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,HTML/CSS;Java;JavaScript;SQL;TypeScript,C;C#;HTML/CSS;Java;JavaScript;Kotlin;Python;SQL,Pandas,Node.js,Jira;Github;Gitlab,Confluence;Jira;Github,Not sure,Neutral,Very important,Just because;Curious about other opportunities...,"Read company media, such as employee blogs or ...",Every few months,Yes,Onboarding? What onboarding?,Yes,Sometimes: 1-2 days per month but less than we...,Ask developers I know/work with;Visit develope...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,Windows,"5,000 to 9,999 employees",Docker;Linux;Windows,Android;Linux;Windows,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;React.js;Spring,ASP.NET;jQuery;React.js;Spring,Just as welcome now as I felt last year,40.0,5,Less than 1 year
550,552,I am a developer by profession,No,25.0,16,Yearly,3500.0,575.0,Turkey,Turkish lira,TRY,MySQL;Oracle;SQLite,Firebase;MongoDB,"Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,"Languages, frameworks, and other technologies ...",Very satisfied,"Iâ€™m not actively looking, but I am open to new...",SQL,Objective-C;Swift,NaN,NaN,Jira,"Github;Slack;Trello;Google Suite (Docs, Meet, ...",No,Neutral,Very important,Curious about other opportunities;Wanting to w...,"Read company media, such as employee blogs or ...",Once a year,NaN,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,10 to 19 employees,Raspberry Pi,iOS;MacOS,I have little or no influence,Straight / Heterosexual,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,Daily or almost daily,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,10.0,6,2
802,804,I am a developer by profession,Yes,NaN,15,Yearly,4000.0,657.0,Turkey,Turkish lira,TRY,Oracle;PostgreSQL,Firebase;MySQL;SQLite,"Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Neither satisfied nor dissatisfied,"Iâ€™m not actively looking, but I am open to new...",Dart;Java;Kotlin,HTML/CSS;JavaScript;TypeScript,Flutter;React Native,NaN,Jira,Github;Gitlab;Slack;Trello,No,Extremely important,Very important,Having a bad day (or week or month) at work;Cu...,"Read company media, such as employee blogs or ...",Every few months,Not sure,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,MacOS,20 to 99 employees,iOS,MacOS;Windows,I have little or no influence,NaN,Yes,"No, not really",I have never participated in Q&A on Stack Over...,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,Angular;Angular.js;jQuery;React.js,Just as welcome now as I felt last year,45.0,10,3
1028,1032,I am a developer by profession,Yes,26.0,18,Monthly,15000.0,29580.0,Turkey,Turkish lira,TRY,Elasticsearch;Firebase;MongoDB,PostgreSQL,"Developer, back-end","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,White or of European descent,Woman,"Languages, frameworks, and other technologies ...",Neither satisfied nor dissatisfied,"Iâ€™m not actively looking, but I am open to new...",Kotlin;Scala,Java,Ansible;Teraform,NaN,Trello,Confluence;Jira;Github;Facebook Workplace;Slac...,No,Extremely important,Very important,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",Once every few years,Not sure,Yes,No,Never,Start a free trial;Ask developers I know/work ...,Annoyed,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,100 to 499 employees,AWS;Google Cloud Platform;Kubernetes;MacOS,Docker;Windows,I have some influence,Straight / Heterosexual,No,"No, not really",NaN,Multiple times per day,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Angular,NaN,Just as welcome now as I felt last year,40.0,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62614,63946,I am a developer by profession,Yes,NaN,20,Monthly,4000.0,7884.0,Turkey,Turkish lira,TRY,NaN,NaN,Data scientist or machine learning specialist;...,Some college/university study without earning ...,Employed full-time,NaN,NaN,NaN,Slightly dissatisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Neutral,Somewhat important,NaN,NaN,NaN,NaN,Yes,NaN,Rarely: 1-2 days per year or less,NaN,NaN,NaN,NaN,NaN,100 to 499 employees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"A business discipline (such as accounting, fin...",NaN,NaN,NaN,9.0,5,2
63199,64587,"I am not primarily a developer, but I write co...",No,NaN,15,Monthly,15000.0,29580.0,Turkey,Turkish lira,TRY,NaN,NaN,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,"Flex time or a flexible schedule;Languages, fr...",Neither satisfied nor dissatisfied,"Iâ€™m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,Yes,Extremely important,Fairly important,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",NaN,NaN,No,NaN,Often: 1-2 days per week or more,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,NaN,20 to 99 employees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Information systems, information technology, o...",NaN,NaN,NaN,45.0,15,10
63205,64594,I am a student who is learning to code,No,NaN,18,NaN,NaN,NaN,Turkey,NaN,NaN,NaN,NaN,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,Office environment or company culture,NaN,"Iâ€™m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,Yes,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot less welcome now than last year,NaN,4,NaN
63387,64795,I am a developer by profession,No,NaN,18,Monthly,13500.0,26628.0,Turkey,Turkish lira,TRY,NaN,NaN,"Designer;Developer, back-end;Developer, deskto...",Some college/university study without earning ...,Employed full-time,NaN,NaN,Flex time or a flexible schedule;Office enviro...,Very satisfied,"Iâ€™m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,Neutral,Very important,Better compensation;Better work/life balance;W...,Company reviews from third party sites (e.g. G...,NaN,NaN,Onboarding? What onboarding?,NaN,Often: 1-2 days per week or more,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,NaN,2 to 9 employees,NaN,NaN,NaN,NaN,Yes,NaN,NaN,Less than once per month or monthly,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,5.0,20,14
63567,64990,"I am not primarily a developer, but I write co...",Yes,NaN,17,Weekly,NaN,NaN,Turkey,United States dollar,USD,NaN,Firebase,"Database administrator;Designer;Developer, bac...",Primary/elementary school,Employed part-time,NaN,NaN,Office environment or company culture,Very dissatisfied,I am actively looking for a job,C#,C;Python,NaN,Pandas,NaN,Jira;Github;Stack Overflow for Teams,Yes,Neutral,Very important,Just because;Better work/life balance;Wanting ...,Personal network - friends or family;Directly ...,Once a year,NaN,Yes,Yes,Often: 1-2 days per week or more,Ask developers I know/work with,Annoyed,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow,Linux-based,100 to 499 employees,NaN,Android;Arduino;Linux,I have a great deal of influence,NaN,Yes,"No, not at all",I have never participated in Q&A on Stack Over...,Daily or almost daily,NaN,NaN,NaN,NaN,NaN,Django,NaN,NaN,2,1

In [ ]:
filt= (mydf['Country']=='Germany') | (mydf['DevType'].str.contains('Developer', na=False))
mydf.loc[filt]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
5,6,I am a developer by profession,No,NaN,14,NaN,NaN,NaN,Germany,European Euro,EUR,NaN,NaN,"Designer;Developer, front-end;Developer, mobile","Secondary school (e.g. American high school, G...",Employed full-time,White or of European descent,Man,Diversity of the company or organization;Langu...,Slightly satisfied,I am not interested in new job opportunities,HTML/CSS;Java;JavaScript,HTML/CSS;Java;JavaScript,NaN,NaN,Github;Slack,Confluence;Github;Slack;Trello,Not sure,NaN,Fairly important,NaN,NaN,Once a year,No,No,No,Never,Ask developers I know/work with;Read ratings o...,Amused,Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Watch help / t...,Windows,NaN,Android,Android;Docker;WordPress,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,A few times per week,Neither easy nor difficult,Appropriate in length,NaN,NaN,React.js,NaN,NaN,NaN,6,4
6,7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,USD,NaN,NaN,"Developer, back-end;Developer, front-end;Devel...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very satisfied,"Iâ€™m not actively looking, but I am open to new...",C#;HTML/CSS;PHP,C#;HTML/CSS;PHP,NaN,NaN,NaN,NaN,Yes,Extremely important,Very important,Better compensation;Growth or leadership oppor...,"Read company media, such as employee blogs or ...",Every few months,Yes,Yes,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Windows,20 to 99 employees,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
7,8,I am a developer by profession,Yes,36.0,12,Yearly,116000.0,116000.0,United States,United States dollar,USD,MongoDB,MariaDB;MySQL;Redis,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Remote work options;Opportunities for professi...,Slightly dissatisfied,"Iâ€™m not actively looking, but I am open to new...",JavaScript,Python;SQL,Unity 3D,Ansible,NaN,Confluence;Jira;Github;Slack;Microsoft Teams;G...,Yes,Extremely important,Not at all important/not necessary,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Yes,No,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,Linux-based,20 to 99 employees,iOS;Slack Apps and Integrations,Docker,I have some influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;React.js;Vue.js,Flask,Just as welcome now as I felt last year,39.0,17,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64446,63640,NaN,Yes,NaN,8,NaN,NaN,NaN,Australia,NaN,NaN,Firebase;Microsoft SQL Server;MongoDB;MySQL;Po...,MongoDB,Academic researcher;Data or business analyst;D...,Primary/elementary school,"Independent contractor, freelancer, or self-em...",NaN,Man,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;J...,Flutter;Node.js;React Native;TensorFlow;Unity ...,Node.js;Unity 3D;Unreal Engine,Jira;Github;Slack;Microsoft Teams;Microsoft Az...,Github;Slack;Microsoft Azure;Google Suite (Doc...,NaN,NaN,Critically important,NaN,NaN,Every few months,No,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Indifferent,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow...,MacOS,NaN,Android;Arduino;AWS;Docker;Google Cloud Platfo...,AWS;Google Cloud Platform;Heroku;iOS;Linux;Mac...,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,A few times per month or weekly,NaN,NaN,No,NaN,Angular;Angular.js;Express;jQuery;React.js;Vue.js,Express;jQuery,Somewhat more welcome now than last year,NaN,6,2
64447,63796,NaN,Yes,NaN,16,NaN,NaN,NaN,Bangladesh,NaN,NaN,NaN,Microsoft SQL Server;MySQL;Oracle;SQLite,"Developer, back-end",NaN,"Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,PHP;Python,C#;HTML/CSS;Java;JavaScript;Swift,NaN,.NET,NaN,Github,NaN,NaN,Somewhat important,NaN,NaN,Once a year,No,NaN,NaN,NaN,Ask developers I know/work with;Visit develope...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Watch help / tutoria...,Windows,NaN,NaN,Android,NaN,NaN,Yes,Neutral,Less than once per month or monthly,A few times per month or weekly,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,6,3
64448,63820,NaN,Yes,NaN,17,NaN,NaN,NaN,Nepal,NaN,NaN,NaN,NaN,"Developer, back-end;Developer, desktop or ente...","Secondary school (e.g. American high school, G...","Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not at all important/not necessary,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Neutral,I have never participated in Q&A on Stack Over...,Less than once per month or monthly,NaN,NaN,NaN,NaN,NaN,NaN,A lot less welcome now than last year,NaN,3,NaN
64449,63994,NaN,Yes,NaN,27,NaN,NaN,NaN,Saudi Arabia,NaN,NaN,NaN,NaN,"Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,"No, not at all",NaN,Less than once per month or monthly,NaN,NaN,NaN,NaN,NaN,NaN,A lot more welcome now than last year,NaN,Less than 1 year,Less than 1 year
64453,64330,NaN,Yes,NaN,5,NaN,NaN,NaN,Thailand,NaN,NaN,NaN,NaN,"Data or business analyst;Developer, mobile;Sen...",Primary/elementary school,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS,C++;HTML/CSS,.NET,.NET,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial,"Hello, old friend",Stack Overflow for Teams (private Q&A for orga...,Watch help / tutorial videos,MacOS,NaN,iOS,iOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN

In [ ]:
mydf.loc[~filt,['Country', 'DevType']] # show only country and devtype column values after filtering.

                  Country              DevType
2      Russian Federation                  NaN
3                 Albania                  NaN
4           United States                  NaN
14                 France                  NaN
20                Belgium                  NaN
...                   ...                  ...
64456       United States  Senior executive/VP
64457             Morocco                  NaN
64458            Viet Nam                  NaN
64459              Poland                  NaN
64460               Spain                  NaN

[18227 rows x 2 columns]

In [ ]:
high_salary=mydf['ConvertedComp']>80000  #check salaries of the records and returns true if they are greater than 80000
mydf.loc[high_salary]
mydf.loc[high_salary,['LanguageWorkedWith', 'WorkWeekHrs','Country','Age','ConvertedComp']]

,LanguageWorkedWith,WorkWeekHrs,Country,Age,ConvertedComp
7,Python;SQL,39.0,United States,36.0,116000.0
15,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,50.0,United Kingdom,45.0,108576.0
17,Bash/Shell/PowerShell;HTML/CSS;Perl,45.0,United States,32.0,1260000.0
18,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;S...,35.0,United States,24.0,83400.0
23,Bash/Shell/PowerShell;Java;Kotlin;PHP;SQL,42.0,Germany,45.0,91883.0
...,...,...,...,...,...
64113,NaN,50.0,United States,NaN,225000.0
64116,NaN,45.0,United States,NaN,150000.0
64127,NaN,NaN,United States,NaN,140000.0
64129,NaN,45.0,United States,NaN,150000.0
64141,NaN,35.0,Germany,NaN,129718.0

In [ ]:
mydf.loc[mydf['Country']=='Turkey'] #list the records whose country column's value is Turkey.

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
292,294,I am a developer by profession,Yes,40.0,19,Monthly,17000.0,33528.0,Turkey,Turkish lira,TRY,MongoDB,IBM DB2;Microsoft SQL Server;Oracle,"Developer, back-end;Developer, full-stack","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,"Iâ€™m not actively looking, but I am open to new...",C#;JavaScript,C#;Java;JavaScript;SQL,.NET;.NET Core;Node.js;React Native,.NET;Node.js;React Native,Github,Jira;Github,Yes,Extremely important,Fairly important,Better compensation;Wanting to work with new t...,Company reviews from third party sites (e.g. G...,Once a year,No,Yes,No,Rarely: 1-2 days per year or less,NaN,Annoyed,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow,Windows,"10,000 or more employees",Heroku,Heroku,I have little or no influence,NaN,Yes,"Yes, definitely",Daily or almost daily,Daily or almost daily,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",Angular;ASP.NET;ASP.NET Core;Express;React.js,Angular;ASP.NET;Express;React.js,Somewhat less welcome now than last year,40.0,20,14
410,412,I am a developer by profession,Yes,23.0,11,Monthly,110000.0,216960.0,Turkey,Turkish lira,TRY,Elasticsearch;MongoDB;PostgreSQL;Redis,Firebase;Microsoft SQL Server;MongoDB;MySQL;Or...,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,Middle Eastern;White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,HTML/CSS;Java;JavaScript;SQL;TypeScript,C;C#;HTML/CSS;Java;JavaScript;Kotlin;Python;SQL,Pandas,Node.js,Jira;Github;Gitlab,Confluence;Jira;Github,Not sure,Neutral,Very important,Just because;Curious about other opportunities...,"Read company media, such as employee blogs or ...",Every few months,Yes,Onboarding? What onboarding?,Yes,Sometimes: 1-2 days per month but less than we...,Ask developers I know/work with;Visit develope...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,Windows,"5,000 to 9,999 employees",Docker;Linux;Windows,Android;Linux;Windows,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;React.js;Spring,ASP.NET;jQuery;React.js;Spring,Just as welcome now as I felt last year,40.0,5,Less than 1 year
550,552,I am a developer by profession,No,25.0,16,Yearly,3500.0,575.0,Turkey,Turkish lira,TRY,MySQL;Oracle;SQLite,Firebase;MongoDB,"Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,"Languages, frameworks, and other technologies ...",Very satisfied,"Iâ€™m not actively looking, but I am open to new...",SQL,Objective-C;Swift,NaN,NaN,Jira,"Github;Slack;Trello;Google Suite (Docs, Meet, ...",No,Neutral,Very important,Curious about other opportunities;Wanting to w...,"Read company media, such as employee blogs or ...",Once a year,NaN,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,10 to 19 employees,Raspberry Pi,iOS;MacOS,I have little or no influence,Straight / Heterosexual,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,Daily or almost daily,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,10.0,6,2
647,649,I am a developer by profession,Yes,23.0,5,NaN,NaN,NaN,Turkey,NaN,NaN,Firebase;MongoDB;Redis,Firebase;Microsoft SQL Server;MongoDB;MySQL,NaN,Some college/university study without earning ...,Student,White or of European descent,Man,"Flex time or a flexible schedule;Languages, fr...",NaN,"Iâ€™m not actively looking, but I am open to new...",C#;Dart;HTML/CSS;Java;JavaScript;Python;TypeSc...,C#;HTML/CSS;Java;JavaScript;SQL,.NET;.NET Core;Node.js;TensorFlow;Torch/PyTorc...,.NET;.NET Core;Node.js;Unity 3D,"Github;Gitlab;Slack;Trello;Google Suite (Docs,...",Github;Gitlab;Slack;Trello,NaN,NaN,NaN,Wanting to share accomplishments with a wider ...,Personal network - friends or family;Read othe...,Every few months,Not sure,NaN,Yes,NaN,Ask developers I know/work with;Visit develope...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,NaN,Android;Arduino;AWS;Docker;Heroku;Kubernetes;M...,Android;Heroku;MacOS;Slack Apps and Integrations,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,A few times per week,Neither easy nor difficult,Appropriate in length,No,NaN,Express;jQuery;React.js,Express;jQuery;React.js,Just as welcome now as I felt last year,NaN,3,NaN
802,804,I am a developer by profession,Yes,NaN,15,Yearly,4000.0,657.0,Turkey,Turkish lira,TRY,Oracle;PostgreSQL,Firebase;MySQL;SQLite,"Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Neither satisfied nor dissatisfied,"Iâ€™m not actively looking, but I am open to new...",Dart;Java;Kotlin,HTML/CSS;JavaScript;TypeScript,Flutter;React Native,NaN,Jira,Github;Gitlab;Slack;Trello,No,Extremely important,Very important,Having a bad day (or week or month) at work;Cu...,"Read company media, such as employee blogs or ...",Every few months,Not sure,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,MacOS,20 to 99 employees,iOS,MacOS;Windows,I have little or no influence,NaN,Yes,"No, not really",I have never participated in Q&A on Stack Over...,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,Angular;Angular.js;jQuery;React.js,Just as welcome now as I felt last year,45.0,10,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63567,64990,"I am not primarily a developer, but I write co...",Yes,NaN,17,Weekly,NaN,NaN,Turkey,United States dollar,USD,NaN,Firebase,"Database administrator;Designer;Developer, bac...",Primary/elementary school,Employed part-time,NaN,NaN,Office environment or company culture,Very dissatisfied,I am actively looking for a job,C#,C;Python,NaN,Pandas,NaN,Jira;Github;Stack Overflow for Teams,Yes,Neutral,Very important,Just because;Better work/life balance;Wanting ...,Personal network - friends or family;Directly ...,Once a year,NaN,Yes,Yes,Often: 1-2 days per week or more,Ask developers I know/work with,Annoyed,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow,Linux-based,100 to 499 employees,NaN,Android;Arduino;Linux,I have a great deal of influence,NaN,Yes,"No, not at all",I have never participated in Q&A on Stack Over...,Daily or almost daily,NaN,NaN,NaN,NaN,NaN,Django,NaN,NaN,2,1
63781,65220,I am a developer by profession,Yes,NaN,NaN,NaN,NaN,NaN,Turkey,NaN,NaN,Elasticsearch;Firebase;MongoDB;MySQL;PostgreSQ...,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL;...,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Dart;Go;PHP;Python;TypeScript,C#;JavaScript;PHP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Every few months,NaN,NaN,Yes,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"No, not really",I have never participated in Q&A on Stack Over...,Daily or almost daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63975,65436,I am a developer by profession,Yes,NaN,NaN,NaN,NaN,NaN,Turkey,NaN,NaN,NaN,NaN,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fairly important,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"A social science (such as anthropology, psycho...",NaN,NaN,NaN,NaN,NaN,NaN
64133,65609,I code primarily as a hobby,Yes,NaN,NaN,NaN,NaN,NaN,Turkey,NaN,NaN,PostgreSQL,Microsoft SQL Server,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Python;R,C#;HTML/CSS;SQL,.NET Core,.NET,Github;Gitlab;Stack Overflow for Teams,Confluence;Jira,NaN,NaN,NaN,NaN,NaN,Once every few years,Not sure,NaN,No,NaN,Start a free trial,Annoyed,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow,Windows,NaN,Android,Windows,NaN,NaN,No,"Yes, somewhat",NaN,A few times per month or weekly,NaN,NaN,NaN,NaN,ASP.NET Core,ASP.NET,Somewhat more welcome now than last year,NaN,NaN,NaN
64166,1264,NaN,Yes,NaN,16,NaN,NaN,NaN,Turkey,NaN,NaN,MySQL;SQLite,MySQL;SQLite,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)","Not employed, and not looking for work",NaN,NaN,NaN,NaN,NaN,C++;Java;Kotlin;Python;SQL;Swift,C++;Java;Kotlin;Python;SQL;Swift,Node.js,Node.js,Github,Github,NaN,NaN,Very important,NaN,NaN,NaN,Not sure,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Annoyed,Stack Overflow (public Q&A for anyone who code...,Meditate;Visit Stack Overflow;Watch help / tut...,Linux-based,NaN,Android;iOS;Linux;Raspberry Pi,Android;iOS;Linux;Raspberry Pi,NaN,NaN,Yes,"Yes, definitely",Daily or almost daily,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,Laravel,A lot less welcome now than last year,NaN,30,NaN

In [ ]:
countries=['Germany', 'France', 'Turkey', 'India']

countr_filt=mydf['Country'].isin(countries)

mydf[countr_filt]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
5,6,I am a developer by profession,No,NaN,14,NaN,NaN,NaN,Germany,European Euro,EUR,NaN,NaN,"Designer;Developer, front-end;Developer, mobile","Secondary school (e.g. American high school, G...",Employed full-time,White or of European descent,Man,Diversity of the company or organization;Langu...,Slightly satisfied,I am not interested in new job opportunities,HTML/CSS;Java;JavaScript,HTML/CSS;Java;JavaScript,NaN,NaN,Github;Slack,Confluence;Github;Slack;Trello,Not sure,NaN,Fairly important,NaN,NaN,Once a year,No,No,No,Never,Ask developers I know/work with;Read ratings o...,Amused,Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Watch help / t...,Windows,NaN,Android,Android;Docker;WordPress,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,A few times per week,Neither easy nor difficult,Appropriate in length,NaN,NaN,React.js,NaN,NaN,NaN,6,4
6,7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,USD,NaN,NaN,"Developer, back-end;Developer, front-end;Devel...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very satisfied,"Iâ€™m not actively looking, but I am open to new...",C#;HTML/CSS;PHP,C#;HTML/CSS;PHP,NaN,NaN,NaN,NaN,Yes,Extremely important,Very important,Better compensation;Growth or leadership oppor...,"Read company media, such as employee blogs or ...",Every few months,Yes,Yes,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Windows,20 to 99 employees,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
14,15,I am a student who is learning to code,Yes,NaN,13,NaN,NaN,NaN,France,NaN,NaN,NaN,MySQL;Oracle,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Student,NaN,Man,"Languages, frameworks, and other technologies ...",NaN,"Iâ€™m not actively looking, but I am open to new...",Assembly;Bash/Shell/PowerShell;C;Go,Bash/Shell/PowerShell;C;HTML/CSS;Java;Python;SQL,NaN,NaN,Github;Gitlab,Github,NaN,NaN,NaN,NaN,NaN,Once every few years,Yes,NaN,No,NaN,Ask developers I know/work with,Annoyed,Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Panic,Linux-based,NaN,Linux,Linux,NaN,Gay or Lesbian,No,"No, not really",NaN,A few times per month or weekly,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,4,NaN
21,22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,INR,NaN,NaN,"Developer, full-stack;Engineer, data","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,NaN,Slightly dissatisfied,I am actively looking for a job,Java;JavaScript;Python,Java;Python,NaN,NaN,NaN,NaN,Not sure,NaN,Very important,Better compensation;Better work/life balance;W...,Company reviews from third party sites (e.g. G...,Every few months,No,Yes,No,Often: 1-2 days per week or more,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Windows,500 to 999 employees,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64402,56263,NaN,Yes,NaN,14,NaN,NaN,NaN,Germany,NaN,NaN,MariaDB;Microsoft SQL Server;MongoDB;Oracle,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Ora...,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Student,White or of European descent,Man,NaN,NaN,NaN,C#;Haskell;Java;Kotlin;Python;Ruby;Rust;Scala;SQL,Assembly;C;C#;Haskell;Java;Kotlin;PHP;Python;R...,Flutter;Keras;Pandas;TensorFlow;Unity 3D,.NET;Flutter;Hadoop;Keras;Pandas;TensorFlow;To...,"Github;Gitlab;Trello;Google Suite (Docs, Meet,...",Github;Gitlab;Slack;Microsoft Azure;Trello;Goo...,NaN,NaN,NaN,NaN,NaN,Once a year,No,NaN,NaN,NaN,Ask developers I know/work with;Read ratings o...,Amused,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Linux-based,NaN,Raspberry Pi,Arduino;Docker;Linux;Microsoft Azure;Raspberry Pi,NaN,Bisexual,Yes,Neutral,I have never participated in Q&A on Stack Over...,A few times per month or weekly,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,Angular;jQuery;Ruby on Rails,Just as welcome now as I felt last year,NaN,7,NaN
64433,61561,NaN,Yes,64.0,18,NaN,NaN,NaN,France,NaN,NaN,MySQL;Oracle,MySQL;Oracle,NaN,NaN,Retired,White or of European descent,Man,NaN,NaN,NaN,Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;P...,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Perl...,Ansible;Apache Spark;Hadoop;Node.js;Puppet,NaN,"Github;Gitlab;Google Suite (Docs, Meet, etc);S...",Github;Gitlab;Stack Overflow for Teams,NaN,NaN,Fairly important,NaN,NaN,Once a year,No,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,NaN,NaN,Android;Arduino;Docker;Linux;Windows;WordPress,Arduino;Docker;Linux;Raspberry Pi;Windows;Word...,NaN,Straight / Heterosexual,Yes,Neutral,Less than once per month or monthly,A few times per month or weekly,Neither easy nor difficult,Appropriate in length,No,"Information systems, information technology, o...",Angular.js;jQuery;React.js;Vue.js,jQuery,A lot more welcome now than last year,NaN,30,NaN
64439,62464,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",NaN,NaN,Man,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I never declared a major,NaN,NaN,NaN,NaN,NaN,NaN
64442,62954,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,SQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ASP.NET;ASP.NET Core;Django;jQuery;Symfony;Vue.js,NaN,NaN,NaN,NaN
64452,64236,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
mydf.loc[countr_filt,'Country']

0        Germany
5        Germany
6          India
14        France
21         India
          ...
64402    Germany
64433     France
64439      India
64442      India
64452      India
Name: Country, Length: 14968, dtype: object

In [ ]:
mydf.loc[countr_filt,'Country'].value_counts()

India      8403
Germany    3890
France     1898
Turkey      777
Name: Country, dtype: int64

In [ ]:
filt=mydf['LanguageWorkedWith'].str.contains('Java',na=False)
mydf.loc[filt]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
5,6,I am a developer by profession,No,NaN,14,NaN,NaN,NaN,Germany,European Euro,EUR,NaN,NaN,"Designer;Developer, front-end;Developer, mobile","Secondary school (e.g. American high school, G...",Employed full-time,White or of European descent,Man,Diversity of the company or organization;Langu...,Slightly satisfied,I am not interested in new job opportunities,HTML/CSS;Java;JavaScript,HTML/CSS;Java;JavaScript,NaN,NaN,Github;Slack,Confluence;Github;Slack;Trello,Not sure,NaN,Fairly important,NaN,NaN,Once a year,No,No,No,Never,Ask developers I know/work with;Read ratings o...,Amused,Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Watch help / t...,Windows,NaN,Android,Android;Docker;WordPress,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,A few times per week,Neither easy nor difficult,Appropriate in length,NaN,NaN,React.js,NaN,NaN,NaN,6,4
8,9,I am a developer by profession,No,30.0,20,NaN,NaN,NaN,Tunisia,United States dollar,USD,NaN,NaN,"Developer, full-stack","Professional degree (JD, MD, etc.)","Independent contractor, freelancer, or self-em...",NaN,Man,Diversity of the company or organization;Remot...,Very dissatisfied,"Iâ€™m not actively looking, but I am open to new...",Python;Rust,HTML/CSS;JavaScript;PHP,NaN,NaN,NaN,"Github;Slack;Trello;Google Suite (Docs, Meet, ...",NaN,NaN,Very important,Curious about other opportunities;Growth or le...,NaN,Once a year,No,Yes,No,Occasionally: 1-2 days per quarter but less th...,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Meditate,Windows,"Just me - I am a freelancer, sole proprietor, ...",NaN,WordPress,NaN,Straight / Heterosexual,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular.js,jQuery,Just as welcome now as I felt last year,50.0,6,4
9,10,I am a developer by profession,Yes,22.0,14,Yearly,25000.0,32315.0,United Kingdom,Pound sterling,GBP,Microsoft SQL Server,Microsoft SQL Server,"Database administrator;Developer, full-stack;D...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;How widely us...,Very satisfied,"Iâ€™m not actively looking, but I am open to new...",HTML/CSS;Java;JavaScript;Python;R;SQL,HTML/CSS;Java;JavaScript;Python;SQL,Pandas;TensorFlow,Pandas,Github;Microsoft Teams,Github;Microsoft Teams,No,Neutral,Fairly important,Curious about other opportunities;Better compe...,Company reviews from third party sites (e.g. G...,Every few months,Yes,Onboarding? What onboarding?,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow,Windows,2 to 9 employees,Android;Linux;Raspberry Pi;Windows,Android;Linux;Raspberry Pi;Windows,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,Easy,Appropriate in length,No,Mathematics or statistics,Flask;jQuery,Flask;jQuery,Somewhat more welcome now than last year,36.0,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64445,63452,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Russian Federation,NaN,NaN,Firebase;MariaDB;Microsoft SQL Server;MongoDB;...,Firebase;IBM DB2;MariaDB;Microsoft SQL Server;...,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C#;C++;HTML/CSS;JavaScri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Arduino;Raspberry Pi;Windows;WordPress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64446,63640,NaN,Yes,NaN,8,NaN,NaN,NaN,Australia,NaN,NaN,Firebase;Microsoft SQL Server;MongoDB;MySQL;Po...,MongoDB,Academic researcher;Data or business analyst;D...,Primary/elementary school,"Independent contractor, freelancer, or self-em...",NaN,Man,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;J...,Flutter;Node.js;React Native;TensorFlow;Unity ...,Node.js;Unity 3D;Unreal Engine,Jira;Github;Slack;Microsoft Teams;Microsoft Az...,Github;Slack;Microsoft Azure;Google Suite (Doc...,NaN,NaN,Critically important,NaN,NaN,Every few months,No,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Indifferent,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow...,MacOS,NaN,Android;Arduino;AWS;Docker;Google Cloud Platfo...,AWS;Google Cloud Platform;Heroku;iOS;Linux;Mac...,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,A few times per month or weekly,NaN,NaN,No,NaN,Angular;Angular.js;Express;jQuery;React.js;Vue.js,Express;jQuery,Somewhat more welcome now than last year,NaN,6,2
64447,63796,NaN,Yes,NaN,16,NaN,NaN,NaN,Bangladesh,NaN,NaN,NaN,Microsoft SQL Server;MySQL;Oracle;SQLite,"Developer, back-end",NaN,"Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,PHP;Python,C#;HTML/CSS;Java;JavaScript;Swift,NaN,.NET,NaN,Github,NaN,NaN,Somewhat important,NaN,NaN,Once a year,No,NaN,NaN,NaN,Ask developers I know/work with;Visit develope...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Watch help / tutoria...,Windows,NaN,NaN,Android,NaN,NaN,Yes,Neutral,Less than once per month or monthly,A few times per month or weekly,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,6,3
64457,64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64460,65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NaN,MariaDB;Microsoft SQL Server,MariaDB;Microsoft SQL Server;MySQL;Oracle,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,C#;HTML/CSS;Java;JavaScript;SQL,C#;HTML/CSS;Java;JavaScript;SQL,.NET Core;Xamarin,.NET;.NET Core,Github;Microsoft Teams,Github,NaN,NaN,Critically important,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Indifferent,NaN,Meditate;Visit Stack Overflow;Go for a walk or...,Windows,NaN,Arduino;Linux;Raspberry Pi;Windows,Android;Arduino;Linux;Raspberry Pi;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [ ]:
type(mydf.iloc[0]) # return the type of it - series

pandas.core.series.Series

In [ ]:
#Modifying the dataframe
#First update all column names 

mystudents.columns # return the column information

Index(['Id', 'Name', 'Surname', 'Grade'], dtype='object')

In [ ]:
mystudents["Name"]

0      Lale
1       Ali
2      Veli
3    Dilara
Name: Name, dtype: object

In [ ]:
type(mystudents["Name"]) # It will return series object type

pandas.core.series.Series

In [ ]:
#we can change the column names by using list comprehension 
mystudents.columns=[s.upper() for s in mystudents.columns]  #By using List Comprehension
mystudents

    ID    NAME SURNAME  GRADE
0   S1    Lale      Al     10
1  S12     Ali      Al      4
2  S15    Veli      Av      6
3  S20  Dilara      Ad      8

In [ ]:
#another way of updating all column names
mystudents.columns=["id","name","surname","grade"]
mystudents

    id    name surname  grade
0   S1    Lale      Al     10
1  S12     Ali      Al      4
2  S15    Veli      Av      6
3  S20  Dilara      Ad      8

In [ ]:
#another way is use to rename method
mystudents.rename(columns={'id':'St id', "name":'FIRST NAME', 'surname': 'LAST NAME', "grade":"Grade"})

  St id FIRST NAME LAST NAME  Grade
0    S1       Lale        Al     10
1   S12        Ali        Al      4
2   S15       Veli        Av      6
3   S20     Dilara        Ad      8

In [ ]:
#It seems that we made the changes on the column but be careful; it does not make the changes permanently;
mystudents

    id    name surname  grade
0   S1    Lale      Al     10
1  S12     Ali      Al      4
2  S15    Veli      Av      6
3  S20  Dilara      Ad      8

In [ ]:
#in order to make the changes in the datafreme you need to set "inplace=True"
mystudents.rename(columns={'id':'St id', "name":'FIRST NAME', 'surname': 'LAST NAME', "grade":"Grade"}, inplace=True)
mystudents

  St id FIRST NAME LAST NAME  Grade
0    S1       Lale        Al     10
1   S12        Ali        Al      4
2   S15       Veli        Av      6
3   S20     Dilara        Ad      8

In [ ]:
#if you want to change only some column names, then use rename with inplace=True

mystudents.rename(columns={"St id":"St ID"}, inplace=True)
mystudents

  St ID FIRST NAME LAST NAME  Grade
0    S1       Lale        Al     10
1   S12        Ali        Al      4
2   S15       Veli        Av      6
3   S20     Dilara        Ad      8

In [ ]:
#Let's call some string methods
mystudents.columns=mystudents.columns.str.replace(' ', '_')
mystudents

  St_ID FIRST_NAME LAST_NAME  Grade
0    S1       Lale        Al     10
1   S12        Ali        Al      4
2   S15       Veli        Av      6
3   S20     Dilara        Ad      8

In [ ]:
mystudents

  St_ID FIRST_NAME LAST_NAME  Grade
0    S1       Lale        Al     10
1   S12        Ali        Al      4
2   S15       Veli        Av      6
3   S20     Dilara        Ad      8

In [ ]:
#Updating the rows

# how can we change a single row content ?

mystudents.loc[1]=['S13','Pinar', 'Ap', 9]
mystudents

  St_ID FIRST_NAME LAST_NAME  Grade
0    S1       Lale        Al     10
1   S13      Pinar        Ap      9
2   S15       Veli        Av      6
3   S20     Dilara        Ad      8

In [ ]:
# if we want to change only some columns in a row

mystudents.loc[2,'Grade']=7
mystudents.loc[2,['FIRST_NAME','LAST_NAME']]=['Tarik','At']
mystudents

  St_ID FIRST_NAME LAST_NAME  Grade
0    S1       Lale        Al     10
1   S13      Pinar        Ap      9
2   S15      Tarik        At      7
3   S20     Dilara        Ad      8

In [ ]:
#you can also use at[] instead of loc[]
mystudents.at[1,'St_ID']='S5'
mystudents

  St_ID FIRST_NAME LAST_NAME  Grade
0    S1       Lale        Al     10
1    S5      Pinar        Ap      9
2   S15      Tarik        At      7
3   S20     Dilara        Ad      8

In [ ]:
filt=(mystudents["FIRST_NAME"]=="Pinar")
mystudents[filt] # it lists the rows satisfying the given condition

  St_ID FIRST_NAME LAST_NAME  Grade
1    S5      Pinar        Ap      9

In [ ]:
#A common mistake 
mystudents[filt]['Grade']=5

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
# Instead, you should use loc
mystudents.loc[filt, 'Grade']=5
mystudents

  St_ID FIRST_NAME LAST_NAME  Grade
0    S1       Lale        Al     10
1    S5      Pinar        Ap      5
2   S15      Tarik        At      7
3   S20     Dilara        Ad      8

In [ ]:
#how to update multiple rows 

mystudents["FIRST_NAME"] # return series object which we can run string methods

0      Lale
1     Pinar
2     Tarik
3    Dilara
Name: FIRST_NAME, dtype: object

In [ ]:
mystudents["FIRST_NAME"].str.upper()

0      LALE
1     PINAR
2     TARIK
3    DILARA
Name: FIRST_NAME, dtype: object

In [ ]:
# Be careful; it will return the processed string but not change the content actually
mystudents

  St_ID FIRST_NAME LAST_NAME  Grade
0    S1       Lale        Al     10
1    S5      Pinar        Ap      5
2   S15      Tarik        At      7
3   S20     Dilara        Ad      8

In [ ]:
#Therefore, you should assign the updated value as follows:
mystudents["FIRST_NAME"]=mystudents["FIRST_NAME"].str.upper()
mystudents

  St_ID FIRST_NAME LAST_NAME  Grade
0    S1       LALE        Al     10
1    S5      PINAR        Ap      5
2   S15      TARIK        At      7
3   S20     DILARA        Ad      8